#!/bin/bash
#
# See:
#   transformBatchFOV -h 
# for usage details
# 
# The template image is used to determine the size of the output image;
# usually, one chooses the target image used for the transformation.
#
# Note: the image resolutions of the moving and template images matters!

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cp=`cat $DIR/bigwarp_classpath.cp`
java -cp "$cp" -Xmx4000m bigwarp.BigWarpBatchTransformFOV "$@"
